# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
    ports:
      - 8081:3306
    volumes:
      - vgdb:/var/lib/mysql
volumes:
  vgdb: