/*
CREATE
*/

CREATE DATABASE BIRULEIBE;
USE BIRULEIBE;

CREATE TABLE ALUNO(ID INT(2) not null PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(255));
CREATE TABLE MATRICULA(ID INT(2) not null PRIMARY KEY AUTO_INCREMENT,NOME VARCHAR(255));
CREATE TABLE ENDERECO(ID INT(2) not null PRIMARY KEY AUTO_INCREMENT,PAIS VARCHAR(255),CIDADE VARCHAR(255),BAIRRO VARCHAR(255),CEP INT(8));

/*
SHOW/DESCRIBE
*/
SHOW TABLES;
DESCRIBE ALUNO;
DESCRIBE MATRICULA;
DESCRIBE ENDERECO;
/*
INSERT/SELECT
*/
INSERT INTO ALUNO (NOME) VALUES ('JOSE');
select * from ALUNO;
